### PR TITLE
Better guide for OS X install

### PR DESCRIPTION
**Pull request by perfaram**

### CODE REVIEW

**Comment by Wallbraker** [comment]
Awesome thanks!

If you look at the other commits they have a area suffix like "volt:" "semantic:" "doc:", I think "doc:" is the most appropriate here.

Hmm is LLVM 3.6.2 packaged for homebrew? I'm using that version from the llvm download repos so we should probably use that. Or have a generic <llvm-version> in the documentation.

**Comment by perfaram** [comment]
I was using LLVM 3.4 because that's what written in the README. Should I use 3.6.2 ?

**Comment by perfaram** [comment]
OK, last commit amended with doc: prefix

**Comment by Wallbraker** [comment]
Thanks!

Hmm its not that clear, its more ment to say "3.4 is required" but the latest should be okay and preferred.

**Comment by perfaram** [comment]
OK, gonna fix.

**Comment by perfaram** [comment]
OK, fixed, but... did you actually try it ?

**Comment by Dav1dde** [comment]
I am using 3.6.2 for a while now, it is even required for Ohm. I think I tried 3.5 on my debian server, since it was the only version in the stable repositories. 

Btw in 3c389f7 it says 3.4 but links to 3.6, also the path in the line below links to 3.4.

We try to keep commit history clean, please rebase all the commits (once it looks good) into one.

Thanks for your help, we are going to try improve the documentation situation a lot in the near future (also see Trello), including the commit guidelines, hopefully that makes contributing in the future easier.

PS: We are really active on chat.freenode.net/#Volt if you want a more realtime feedback!

**Comment by perfaram** [comment]
OK !

**Comment by perfaram** [comment]
Migrated to cleaner history : #8

**Pull request closed without merging**
